version: '3.8'

services:
  sementique_app:
    build:
      context: .
    restart: always
    ports:
      - ${PORT_APP}:8501
    volumes:
      - ./data:/data
    networks:
      - sementique-ales

networks:
  sementique-ales:
    name: sementique-ales
    driver: bridge